import os

ORIGIN = os.getenv("FLIGHT_ORIGIN", "TPE")

DESTINATION = os.getenv("FLIGHT_DESTINATION", "TYO")

DEPARTURE_DATE = os.getenv("FLIGHT_DATE", "2027-02-03")

RETURN_DATE = os.getenv("FLIGHT_RETURN_DATE", "2027-02-08")

ADULT_COUNT = 1

CHILD_COUNT = 0

INFANT_COUNT = 0